import os, sys, subprocess
def die(msg, code=2): sys.stderr.write(msg + "\n"); sys.exit(code)
if len(sys.argv) < 2: die("ERROR: Missing input path argument. Usage: analyze_clip_guard.py <input_path>")
inp = sys.argv[1].strip().strip('"').strip("'")
if not inp or inp.lower()=="undefined": die("ERROR: Input path is empty or 'undefined'")
if not os.path.exists(inp): die(f"ERROR: Input not found on disk: {inp}", 3)
env = os.environ.copy()
env.setdefault("LMSTUDIO_MODEL","llama3-llava-next-8b:2")
env.setdefault("LMSTUDIO_URL","http://localhost:1234/v1/chat/completions")
env.setdefault("META_DIR", r"E:\n8n-docker\data\meta")
env.setdefault("TMP_DIR",  r"E:\n8n-docker\data\tmp")
analyzer = env.get("ANALYZER_PY", r"E:\n8n-docker\scripts\analyze_clip.py")
proc = subprocess.run([sys.executable, analyzer, inp], env=env, capture_output=True, text=True)
sys.stdout.write(proc.stdout); sys.stderr.write(proc.stderr); sys.exit(proc.returncode)
